version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword      # Root password for MySQL
      MYSQL_DATABASE: yourdatabase           # Initial database name
      MYSQL_USER: youruser                   # Non-root user
      MYSQL_PASSWORD: youruserpassword       # Non-root user password
    volumes:
      - db-data:/var/lib/mysql               # Persist MySQL data
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql                        # MySQL service name
      PMA_PORT: 3306                         # MySQL port
      MYSQL_ROOT_PASSWORD: yourpassword      # Root password for phpMyAdmin
    ports:
      - "8080:80"                            # Host port:Container port
    depends_on:
      mysql:
        condition: service_healthy           # Wait for MySQL to be healthy
    networks:
      - webnet

volumes:
  db-data:                                   # Named volume for MySQL data

networks:
  webnet:                                    # Custom network for all services