version: '3.8'

services:
  mysql:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "yourpassword"
      MYSQL_DATABASE: "yourdatabase"
      MYSQL_USER: "youruser"
      MYSQL_PASSWORD: "youruserpassword"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pyourpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      MYSQL_ROOT_PASSWORD: "yourpassword"
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - webnet

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    depends_on:
      - phpmyadmin  # Assuming Nginx serves as a reverse proxy to phpMyAdmin
      - redis      # Optional dependency example

volumes:
  db-data:

networks:
  webnet: