version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

  redis:
    image: redis:alpine
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet: