version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: youruser
      MYSQL_PASSWORD: youruserpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webnet

  redis:
    image: redis:alpine
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - webnet

volumes:
  db-data:

networks:
  webnet: